//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSharpPlayground {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SynaxHighlight {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SynaxHighlight() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSharpPlayground.SynaxHighlight", typeof(SynaxHighlight).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Color name=&quot;Comment&quot; foreground=&quot;#FF579835&quot; /&gt;
        ///&lt;Color name=&quot;Keyword&quot; foreground=&quot;#FF4091CA&quot; /&gt;
        ///&lt;Color name=&quot;SideEffect&quot; foreground=&quot;#FFFEAD1D&quot; /&gt;
        ///&lt;Color name=&quot;NumberLiteral&quot; foreground=&quot;#FFB5CEA8&quot; /&gt;
        ///&lt;Color name=&quot;StringLiteral&quot; foreground=&quot;#FFD69D85&quot; /&gt;
        ///&lt;Color name=&quot;StringFormat&quot; foreground=&quot;#FF4EDCB0&quot;/&gt;
        ///&lt;Color name=&quot;Types&quot; foreground=&quot;#FF4EC9B0&quot;/&gt;
        ///&lt;Color name=&quot;Parttens&quot; foreground=&quot;#FFB8D7A3&quot;/&gt;
        ///&lt;Color name=&quot;Preprocessor&quot; foreground=&quot;#FF9B9B9B&quot;/&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string DarkThemeColors {
            get {
                return ResourceManager.GetString("DarkThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Color name=&quot;Comment&quot; foreground=&quot;#FF579835&quot; /&gt;
        ///&lt;Color name=&quot;Keyword&quot; foreground=&quot;#FF4091CA&quot; /&gt;
        ///&lt;Color name=&quot;SideEffect&quot; foreground=&quot;#FFFEAD1D&quot; /&gt;
        ///&lt;Color name=&quot;NumberLiteral&quot; foreground=&quot;#FFB5CEA8&quot; /&gt;
        ///&lt;Color name=&quot;StringLiteral&quot; foreground=&quot;#FFD69D85&quot; /&gt;
        ///&lt;Color name=&quot;StringFormat&quot; foreground=&quot;#FF4EDCB0&quot;/&gt;
        ///&lt;Color name=&quot;Types&quot; foreground=&quot;#FF4EC9B0&quot;/&gt;
        ///&lt;Color name=&quot;Parttens&quot; foreground=&quot;#FFB8D7A3&quot;/&gt;
        ///&lt;Color name=&quot;Preprocessor&quot; foreground=&quot;#FF9B9B9B&quot;/&gt;
        /// 的本地化字符串。
        /// </summary>
        internal static string LightThemeColors {
            get {
                return ResourceManager.GetString("LightThemeColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;SyntaxDefinition name=&quot;Yukimi&quot; xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///
        ///  &lt;!-- Colors --&gt;
        ///	
        ///	&lt;RuleSet&gt;
        ///    &lt;!-- Preprocessor --&gt;
        ///    &lt;Span color=&quot;Preprocessor&quot; begin=&quot;#&quot;/&gt;
        ///    
        ///		&lt;!-- ================ Comments ================ --&gt;
        ///		&lt;!-- Line Comment --&gt;
        ///		&lt;Span color=&quot;Comment&quot; begin=&quot;//&quot; /&gt;
        ///		
        ///		&lt;!-- Block Comment --&gt;
        ///		&lt;Span color=&quot;Comment&quot; multiline=&quot;true&quot;&gt;
        ///			&lt;Begin&gt;\(\*&lt;/Begin&gt;
        ///			&lt;End&gt;\*\)&lt;/End&gt;
        ///		&lt;/Span&gt;
        ///    
        ///    
        ///    
        ///    &lt;!-- == [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Synax {
            get {
                return ResourceManager.GetString("Synax", resourceCulture);
            }
        }
    }
}
